/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code org.simqle.generator
*/

package org.simqle.sql;

import org.simqle.Sql;
import org.simqle.SqlContext;




/**
* Represents
* from_clause
* symbol of SQL language.

*/
public  interface from_clause {

    
    void add_table(table_reference table);

        /**
        * Creates an Sql representing <code>this</code>
        * @param context the Sql construction context
        * @return sql conforming to <code>this</code> syntax
        */
        
    Sql z$create$from_clause(SqlContext context);

        /**
        * Prepares SQL context for construction of from_clause Sql clause
        * @param context the Sql construction context
        */
        
    void z$prepare$from_clause(SqlContext context);

}
