/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

import java.sql.SQLException;

import org.simqle.*;
import org.simqle.sql.*;
<#list imports as import>${import}
</#list>

${declaration} implements <#list implementedInterfaces as interfaces>${interfaces}<#if interfaces_has_next>,
        </#if></#list> {

${body}

}
