/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};


<#list imports as import>${import}
</#list>

class ${classPair.base.className} ${classPair.base.extendsStatement} ${classPair.base.implementsStatement} ${classPair.base.body}

public class ${classPair.extension.className} ${classPair.extension.extendsStatement} ${classPair.extension.implementsStatement} ${classPair.extension.body}
