/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

import java.sql.SQLException;
import org.simqle.core.FromClause;

<#list imports as import>${import}
</#list>

import org.simqle.*;
import static org.simqle.SqlTerminal.*;

/**
* This class implements Sql language productions according to sql-2003 specification.
*/

public class GenericSqlFactory extends SqlFactory {

<#list productions as production>
    public ${production.declaration} {

${production.implementation}

}
// end of ${production.methodName}

</#list>

}
