/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

<#list definition.importLines as import>${import}
</#list>

${definition.comment}
/**
* Represents
* ${name}
* symbol of SQL language.
<#if typeParameters != "">
* @param <${definition.typeParameters[0]}> type, to which this object can be converted when appears in the result set</#if>
*/
<#list modifiers as modifier>${modifier} </#list> interface ${name}${typeParameters} ${extendsList}{
<#list definition.body.methods as method>${method.comment}
    ${method.declaration};

</#list>
<#list definition.body.otherDeclarations as declaration>${declaration}

</#list>
}
