/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

<#list imports as import>${import}
</#list>

${comment}
/**
* Represents
* ${name}
* symbol of SQL language.
<#if typeParameters != "">
* @param <${firstTypeParameter}> type, to which this object can be converted when appears in the result set</#if>
*/
<#list modifiers as modifier>${modifier} </#list> interface ${name}${typeParameters} ${extendsList}{
<#list methods as method>${method.comment}
    ${method.signature};

</#list>
<#list otherDeclarations as declaration>${declaration}

</#list>
}
