/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

<#list imports as import>${import}
</#list>

import org.simqle.*;
import static org.simqle.SqlTerminal.*;

/**
* This class defines methods, implementing Sql language productions.
* Method names are self-descriptive.
*/

public abstract class SqlFactory {

    public static SqlFactory getInstance() {
        return new GenericSqlFactory();
    }

<#list productions as production>
    public abstract ${production.declaration};
</#list>

}
