/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code generator
*/

package ${packageName};

<#list imports as import>${import}
</#list>

import org.symqle.simqle.*;
import static org.symqle.simqle.SqlTerminal.*;

/**
* This class defines methods, implementing Sql language productions.
* Method names are self-descriptive.
*/

public abstract class SqlFactory {

    public static SqlFactory getInstance() {
        return new GenericSqlFactory();
    }

<#list factoryMethods as factoryMethod>
    public abstract ${factoryMethod.methodDeclaration.declarationWithoutModifiers};
</#list>

}
