/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code org.simqle.generator
*/

package org.simqle.sql;

import org.simqle.Element;
import org.simqle.Query;
import org.simqle.Scalar;
import org.simqle.SqlContext;

// this line comment
/* this multiline comment
*/
/**
* and this javadoc
* will all appear in the interface comment
*/

/**
* Represents
* select_statement_scalar
* symbol of SQL language.
* @param <T> type, to which this object can be converted when appears in the result set
*/
public  interface select_statement_scalar<T> extends Scalar<T>{
        /**
        * Converts data from row element to Java object of type T
        * @param element row element containing the data
        * @return object of type T, may be null
        */
        
    T value(Element element);

        /**
        * Creates a Query
        * @param context the Sql construction context
        * @return query conforming to <code>this</code> syntax
        */
        
    Query<T> z$create$select_statement_scalar(SqlContext context);

        /**
        * Prepares SQL context for construction of select_statement_scalar Sql clause
        * @param context the Sql construction context
        */
        
    void z$prepare$select_statement_scalar(SqlContext context);

}
