/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code org.simqle.generator
*/

package org.symqle.sql;

import org.symqle.Element;
import org.symqle.Scalar;
import org.symqle.Sql;
import org.symqle.SqlContext;




/**
* Represents
* boolean_expression
* symbol of SQL language.

*/
public  interface boolean_expression extends Scalar<Boolean>, Serializable{
        /**
        * Converts data from row element to Java object of type Boolean
        * @param element row element containing the data
        * @return object of type Boolean, may be null
        */
        
    Boolean value(Element element);

        /**
        * Creates an Sql representing <code>this</code>
        * @param context the Sql construction context
        * @return sql conforming to <code>this</code> syntax
        */
        
    Sql z$create$boolean_expression(SqlContext context);

        /**
        * Prepares SQL context for construction of boolean_expression Sql clause
        * @param context the Sql construction context
        */
        
    void z$prepare$boolean_expression(SqlContext context);

}
