/*
* Copyright (c) 2010-2011 Alexander Izyurov
* This file is generated by Simqle code org.simqle.generator
*/

package org.simqle.sql;

import org.simqle.Query;
import org.simqle.SqlContext;


/**
* interface1 select_statement
*/

/**
* Represents
* select_statement
* symbol of SQL language.
* @param <T> type, to which this object can be converted when appears in the result set
*/
public  interface select_statement<T> {
        /**
        * Creates a Query
        * @param context the Sql construction context
        * @return query conforming to <code>this</code> syntax
        */
        
    Query<T> z$create$select_statement(SqlContext context);

        /**
        * Prepares SQL context for construction of select_statement Sql clause
        * @param context the Sql construction context
        */
        
    void z$prepare$select_statement(SqlContext context);

}
